-- CREATE DATABASE `spelling_bee`;

USE `heroku_b07eeb49085b99d`;

CREATE TABLE `words` (
  id int NOT NULL AUTO_INCREMENT,
  word varchar(255) NOT NULL,
  translation varchar(255) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO `words`(`word`, `translation`) VALUES ("ABILITY", "HABILIDADE");
INSERT INTO `words`(`word`, `translation`) VALUES ("ABOUT", "SOBRE");
INSERT INTO `words`(`word`, `translation`) VALUES ("ABOVE", "ACIMA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ABROAD", "EXTERIOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("ACCENT", "SOTAQUE");
INSERT INTO `words`(`word`, `translation`) VALUES ("ACTION", "AÇÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ACTOR", "ATOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("ACTRESS", "ATRIZ");
INSERT INTO `words`(`word`, `translation`) VALUES ("AEROBICS", "AERÓBICA");
INSERT INTO `words`(`word`, `translation`) VALUES ("AFTER", "DEPOIS");
INSERT INTO `words`(`word`, `translation`) VALUES ("AGE", "IDADE");
INSERT INTO `words`(`word`, `translation`) VALUES ("AIRPORT", "AEROPORTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ALMOST", "QUASE");
INSERT INTO `words`(`word`, `translation`) VALUES ("ALONE", "SOZINHO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ALPHABET", "ALFABETO");
INSERT INTO `words`(`word`, `translation`) VALUES ("AMAZING", "INCRÍVEL");
INSERT INTO `words`(`word`, `translation`) VALUES ("ANIMATION", "ANIMAÇÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ANOTHER", "OUTRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ARM", "BRAÇO");
INSERT INTO `words`(`word`, `translation`) VALUES ("AROUND", "AO REDOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("AUGUST", "AGOSTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("AUNT", "TIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("AVOCADO", "ABACATE");
INSERT INTO `words`(`word`, `translation`) VALUES ("BACKPACK", "MOCHILA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BAKER", "PADEIRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("BAKERY", "PADARIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BASEBALL", "BEISEBOL");
INSERT INTO `words`(`word`, `translation`) VALUES ("BATHROOM", "BANHEIRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEANS", "FEIJÕES");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEARD", "BARBA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEAST", "ANIMAL");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEEF", "BIFE");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEHIND", "ATRÁS");
INSERT INTO `words`(`word`, `translation`) VALUES ("BELLBOY", "MENSAGEIRO DE HOTEL");
INSERT INTO `words`(`word`, `translation`) VALUES ("BEVERAGE", "BEBIDA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BLOUSE", "BLUSA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BLUE", "AZUL");
INSERT INTO `words`(`word`, `translation`) VALUES ("BORING", "CHATO");
INSERT INTO `words`(`word`, `translation`) VALUES ("BOTTLE", "GARRAFA");
INSERT INTO `words`(`word`, `translation`) VALUES ("BROWN", "MARROM");
INSERT INTO `words`(`word`, `translation`) VALUES ("CAKE", "BOLO");
INSERT INTO `words`(`word`, `translation`) VALUES ("CALORIES", "CALORIAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("CANDLE", "VELA");
INSERT INTO `words`(`word`, `translation`) VALUES ("CAST", "ELENCO");
INSERT INTO `words`(`word`, `translation`) VALUES ("CHANNEL", "CANAL");
INSERT INTO `words`(`word`, `translation`) VALUES ("CLASSMATE", "COLEGA DE CLASSE");
INSERT INTO `words`(`word`, `translation`) VALUES ("CLOTHES", "ROUPAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("COAT", "CASACO DE FRIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("COLLEGE", "FACULDADE");
INSERT INTO `words`(`word`, `translation`) VALUES ("COUSIN", "PRIMO");
INSERT INTO `words`(`word`, `translation`) VALUES ("DRIVE", "DIRIGIR");
INSERT INTO `words`(`word`, `translation`) VALUES ("DARLING", "QUERIDO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("DENTIST", "DENTISTA");
INSERT INTO `words`(`word`, `translation`) VALUES ("DINNER", "JANTAR");
INSERT INTO `words`(`word`, `translation`) VALUES ("DIRECTION", "DIREÇÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("DISCOUNT", "DESCONTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("DRAGON", "DRAGÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("EAT", "COMER");
INSERT INTO `words`(`word`, `translation`) VALUES ("EARTH", "TERRA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ENERGY", "ENERGIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ERASER", "BORRACHA");
INSERT INTO `words`(`word`, `translation`) VALUES ("EVENT", "EVENTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("EVERYDAY", "DIÁRIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("EXAMPLE", "EXEMPLO");
INSERT INTO `words`(`word`, `translation`) VALUES ("EXCITED", "ANIMADO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("EXPENSES", "GASTOS");
INSERT INTO `words`(`word`, `translation`) VALUES ("EXPRESSION", "EXPRESSÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("FAIR", "JUSTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("FALSE", "FALSO");
INSERT INTO `words`(`word`, `translation`) VALUES ("FAMOUS", "FAMOSO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("FANCY", "CHIQUE");
INSERT INTO `words`(`word`, `translation`) VALUES ("FANTASY", "FANTASIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("FAVORITE", "FAVORITO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("FITNESS", "BOA FORMA");
INSERT INTO `words`(`word`, `translation`) VALUES ("FLIGHT", "VOO");
INSERT INTO `words`(`word`, `translation`) VALUES ("FLOWER", "FLOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("FOLLOW", "SEGUIR");
INSERT INTO `words`(`word`, `translation`) VALUES ("FOX", "RAPOSA");
INSERT INTO `words`(`word`, `translation`) VALUES ("FRIEND", "AMIGO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("FUN", "DIVERSÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("FUTURE", "FUTURO");
INSERT INTO `words`(`word`, `translation`) VALUES ("GARDEN", "JARDIM");
INSERT INTO `words`(`word`, `translation`) VALUES ("GENERAL", "GERAL");
INSERT INTO `words`(`word`, `translation`) VALUES ("GIFT", "PRESENTE");
INSERT INTO `words`(`word`, `translation`) VALUES ("GLOVES", "LUVAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("GOSSIP", "FOFOCA");
INSERT INTO `words`(`word`, `translation`) VALUES ("GRANDMOTHER", "AVÓ");
INSERT INTO `words`(`word`, `translation`) VALUES ("GUIDE", "GUIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("GUITAR", "VIOLÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("HONEY", "MEL");
INSERT INTO `words`(`word`, `translation`) VALUES ("HARD", "DIFÍCIL");
INSERT INTO `words`(`word`, `translation`) VALUES ("HEAD", "CABEÇA");
INSERT INTO `words`(`word`, `translation`) VALUES ("HIGH", "ALTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("HOLIDAY", "FERIADO");
INSERT INTO `words`(`word`, `translation`) VALUES ("HOUSEWORK", "AFAZERES DOMÉSTICOS");
INSERT INTO `words`(`word`, `translation`) VALUES ("HUNDRED", "CEM");
INSERT INTO `words`(`word`, `translation`) VALUES ("JACKET", "JAQUETA");
INSERT INTO `words`(`word`, `translation`) VALUES ("JAPAN", "JAPÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("JELLY", "GELEIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("JOYSTICK", "CONTROLE");
INSERT INTO `words`(`word`, `translation`) VALUES ("JUICE", "SUCO");
INSERT INTO `words`(`word`, `translation`) VALUES ("JUNGLE", "SELVA");
INSERT INTO `words`(`word`, `translation`) VALUES ("JUST", "SOMENTE");
INSERT INTO `words`(`word`, `translation`) VALUES ("JUSTICE", "JUSTIÇA");
INSERT INTO `words`(`word`, `translation`) VALUES ("KEEPER", "GUARDA; ZELADOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("KEY", "CHAVE");
INSERT INTO `words`(`word`, `translation`) VALUES ("KIND", "TIPO");
INSERT INTO `words`(`word`, `translation`) VALUES ("KING", "REI");
INSERT INTO `words`(`word`, `translation`) VALUES ("KITE", "PIPA");
INSERT INTO `words`(`word`, `translation`) VALUES ("LAPTOP", "LAPTOP");
INSERT INTO `words`(`word`, `translation`) VALUES ("LAUGHS", "RISADAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("LAZY", "PREGUIÇOSO");
INSERT INTO `words`(`word`, `translation`) VALUES ("LEAFLET", "FOLHETO");
INSERT INTO `words`(`word`, `translation`) VALUES ("LISTEN", "OUVIR");
INSERT INTO `words`(`word`, `translation`) VALUES ("LOCKER", "ARMÁRIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("LONELY", "SOLITÁRIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("LOVELY", "AMÁVEL");
INSERT INTO `words`(`word`, `translation`) VALUES ("LUNCH", "ALMOÇO");
INSERT INTO `words`(`word`, `translation`) VALUES ("MAZE", "LABIRINTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("MANY", "MUITOS(AS)");
INSERT INTO `words`(`word`, `translation`) VALUES ("MAYO", "MAIONESE");
INSERT INTO `words`(`word`, `translation`) VALUES ("MEETING", "REUNIÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("MEMORY", "MEMÓRIA");
INSERT INTO `words`(`word`, `translation`) VALUES ("MORNING", "MANHÃ");
INSERT INTO `words`(`word`, `translation`) VALUES ("MOVIES", "FILMES");
INSERT INTO `words`(`word`, `translation`) VALUES ("NOVEL", "ROMANCE");
INSERT INTO `words`(`word`, `translation`) VALUES ("NATURE", "NATUREZA");
INSERT INTO `words`(`word`, `translation`) VALUES ("NECK", "PESCOÇO");
INSERT INTO `words`(`word`, `translation`) VALUES ("NEGATIVE", "NEGATIVO");
INSERT INTO `words`(`word`, `translation`) VALUES ("NEWSPAPER", "JORNAL");
INSERT INTO `words`(`word`, `translation`) VALUES ("NOISE", "BARULHO");
INSERT INTO `words`(`word`, `translation`) VALUES ("NOVEMBER", "NOVEMBRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("OPPOSITE", "OPOSTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("OBJECT", "OBJETO");
INSERT INTO `words`(`word`, `translation`) VALUES ("ORANGE", "LARANJA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ORDINARY", "COMUM");
INSERT INTO `words`(`word`, `translation`) VALUES ("OWL", "CORUJA");
INSERT INTO `words`(`word`, `translation`) VALUES ("PAINKILLER", "ANALGÉSICO");
INSERT INTO `words`(`word`, `translation`) VALUES ("PAJAMAS", "PIJAMAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("PANCAKE", "PANQUECA");
INSERT INTO `words`(`word`, `translation`) VALUES ("PARTNER", "PARCEIRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("PERHAPS", "TALVEZ");
INSERT INTO `words`(`word`, `translation`) VALUES ("PIRATE", "PIRATAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("PLANET", "PLANETA");
INSERT INTO `words`(`word`, `translation`) VALUES ("QUIET", "CALADO");
INSERT INTO `words`(`word`, `translation`) VALUES ("QUEEN", "RAINHA");
INSERT INTO `words`(`word`, `translation`) VALUES ("QUESTION", "QUESTÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("QUITE", "BASTANTE");
INSERT INTO `words`(`word`, `translation`) VALUES ("RAINBOW", "ARCO-ÍRIS");
INSERT INTO `words`(`word`, `translation`) VALUES ("READER", "LEITOR");
INSERT INTO `words`(`word`, `translation`) VALUES ("READY", "PRONTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("REASON", "RAZÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("RECIPE", "RECEITA");
INSERT INTO `words`(`word`, `translation`) VALUES ("RELATED", "RELACIONADO");
INSERT INTO `words`(`word`, `translation`) VALUES ("REPLY", "RESPOSTA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ROMANCE", "ROMANCE");
INSERT INTO `words`(`word`, `translation`) VALUES ("RUDE", "RUDE");
INSERT INTO `words`(`word`, `translation`) VALUES ("SALAD", "SALADA");
INSERT INTO `words`(`word`, `translation`) VALUES ("SCREEN", "TELA");
INSERT INTO `words`(`word`, `translation`) VALUES ("SEASON", "ESTAÇÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("SECRET", "SEGREDO");
INSERT INTO `words`(`word`, `translation`) VALUES ("SENTENCE", "SENTENÇA");
INSERT INTO `words`(`word`, `translation`) VALUES ("SERIOUS", "SÉRIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("SHARK", "TUBARÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("SHELF", "PRATELEIRA");
INSERT INTO `words`(`word`, `translation`) VALUES ("SHOPPING", "COMPRAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("SOUP", "SOPA");
INSERT INTO `words`(`word`, `translation`) VALUES ("TABLE", "MESA");
INSERT INTO `words`(`word`, `translation`) VALUES ("TALL", "ALTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("TATTOO", "TATUAGEM");
INSERT INTO `words`(`word`, `translation`) VALUES ("TERRIFIC", "ÓTIMO");
INSERT INTO `words`(`word`, `translation`) VALUES ("TOMATO", "TOMATE");
INSERT INTO `words`(`word`, `translation`) VALUES ("TOOTH", "DENTE");
INSERT INTO `words`(`word`, `translation`) VALUES ("TRADITION", "TRADIÇÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("TRAVEL", "VIAJAR");
INSERT INTO `words`(`word`, `translation`) VALUES ("UNCLE", "TIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("UNICORN", "UNICÓRNIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("UNIT", "UNIDADE");
INSERT INTO `words`(`word`, `translation`) VALUES ("UNIVERSITY", "UNIVERSIDADE");
INSERT INTO `words`(`word`, `translation`) VALUES ("USEFUL", "ÚTIL");
INSERT INTO `words`(`word`, `translation`) VALUES ("VACATION", "FÉRIAS");
INSERT INTO `words`(`word`, `translation`) VALUES ("VAMPIRE", "VAMPIRO");
INSERT INTO `words`(`word`, `translation`) VALUES ("VEGGIE", "VEGETARIANO");
INSERT INTO `words`(`word`, `translation`) VALUES ("VERY", "MUITO");
INSERT INTO `words`(`word`, `translation`) VALUES ("VICTIM", "VÍTIMA");
INSERT INTO `words`(`word`, `translation`) VALUES ("VOLCANO", "VULCÃO");
INSERT INTO `words`(`word`, `translation`) VALUES ("WEDDING", "CASAMENTO");
INSERT INTO `words`(`word`, `translation`) VALUES ("WARM", "QUENTE, MORNO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("WATCH", "RELÓGIO");
INSERT INTO `words`(`word`, `translation`) VALUES ("WEATHER", "TEMPO");
INSERT INTO `words`(`word`, `translation`) VALUES ("WEDNESDAY", "QUARTA-FEIRA");
INSERT INTO `words`(`word`, `translation`) VALUES ("WOLF", "LOBO");
INSERT INTO `words`(`word`, `translation`) VALUES ("WORK", "TRABALHAR");
INSERT INTO `words`(`word`, `translation`) VALUES ("WORM", "MINHOCA");
INSERT INTO `words`(`word`, `translation`) VALUES ("WORRIED", "PREOCUPADO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("WRITTEN", "ESCRITO");
INSERT INTO `words`(`word`, `translation`) VALUES ("YEAR", "ANO");
INSERT INTO `words`(`word`, `translation`) VALUES ("YOGA", "YOGA");
INSERT INTO `words`(`word`, `translation`) VALUES ("YOUR", "SEU, SUA");
INSERT INTO `words`(`word`, `translation`) VALUES ("YOURSELF", "VOCÊ MESMO(A)");
INSERT INTO `words`(`word`, `translation`) VALUES ("ZEBRA", "ZEBRA");
INSERT INTO `words`(`word`, `translation`) VALUES ("ZOO", "ZOOLÓGICO");
